version: "2"
plugins:
  eslint:
    enabled: true
    channel: "eslint-7"
    config:
      config: ./.eslintrc.js
      extensions:
        - .js
        - .jsx
        - .ts
        - .tsx
    checks:
      import/extensions:
        enabled: false
  duplication:
    enabled: false
